-- Seed default modules and permissions for the CloudWrkz API.
-- Idempotent: re-running (e.g. migrate) will upsert by key.
-- Run automatically with: sqlx migrate run (or on API startup via migrate!()).

-- Default modules (enabled so /me returns them)
INSERT INTO modules (id, key, name, description, enabled, config, created_at, updated_at)
VALUES
  (gen_random_uuid()::text, 'tickets', 'Tickets', 'Support ticket tracking', true, '{}'::jsonb, NOW(), NOW()),
  (gen_random_uuid()::text, 'timetracking', 'Time Tracking', 'Time entries and timers', true, '{}'::jsonb, NOW(), NOW()),
  (gen_random_uuid()::text, 'todos', 'Todos', 'Task and todo management', true, '{}'::jsonb, NOW(), NOW()),
  (gen_random_uuid()::text, 'links', 'Links', 'Bookmarks and link collections', true, '{}'::jsonb, NOW(), NOW())
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  enabled = EXCLUDED.enabled,
  config = EXCLUDED.config,
  updated_at = NOW();

-- Default permissions (required for check_permission and admin/UI)
INSERT INTO permissions (id, key, name, description, category, module, created_at, updated_at)
VALUES
  (gen_random_uuid()::text, 'tickets.view', 'View Tickets', 'View tickets assigned to user or user''s groups', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.view_all', 'View All Tickets', 'View all tickets regardless of assignment', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.create', 'Create Tickets', 'Create new support tickets', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.update', 'Update Tickets', 'Update existing tickets', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.delete', 'Delete Tickets', 'Delete tickets', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.assign', 'Assign Tickets', 'Assign tickets to users or groups', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.comment', 'Comment on Tickets', 'Add comments to tickets', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.time_entries.view', 'View Ticket Time Entries', 'View time entries in ticket detail view', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.time_entries.create', 'Create Ticket Time Entries', 'Create time entries from ticket detail view', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.merge', 'Merge Tickets', 'Merge one ticket into another', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.bulk_update', 'Bulk Update Tickets', 'Perform bulk update operations on multiple tickets', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.bulk_delete', 'Bulk Delete Tickets', 'Delete multiple tickets in a single operation', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.bulk_archive', 'Bulk Archive Tickets', 'Archive multiple tickets in a single operation', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.bulk_unarchive', 'Bulk Unarchive Tickets', 'Unarchive multiple tickets in a single operation', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.archive', 'Archive Tickets', 'Archive and unarchive individual tickets', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.comments.agent_only', 'Create Internal Ticket Comments', 'Create agent-only/internal comments on tickets', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.comments.view_internal', 'View Internal Ticket Comments', 'View agent-only/internal comments on tickets', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.export', 'Export Tickets', 'Export ticket data for reporting or backup', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'tickets.reports.view', 'View Ticket Reports', 'View ticket analytics and reports', 'tickets', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'time_tracking.view', 'View Time Entries', 'View own time entries', 'time_tracking', 'timetracking', NOW(), NOW()),
  (gen_random_uuid()::text, 'time_tracking.view_all', 'View All Time Entries', 'View all time entries', 'time_tracking', 'timetracking', NOW(), NOW()),
  (gen_random_uuid()::text, 'time_tracking.create', 'Create Time Entries', 'Create new time entries', 'time_tracking', 'timetracking', NOW(), NOW()),
  (gen_random_uuid()::text, 'time_tracking.update', 'Update Time Entries', 'Update time entries', 'time_tracking', 'timetracking', NOW(), NOW()),
  (gen_random_uuid()::text, 'time_tracking.delete', 'Delete Time Entries', 'Delete time entries', 'time_tracking', 'timetracking', NOW(), NOW()),
  (gen_random_uuid()::text, 'todos.view', 'View Todos', 'View todos', 'todos', 'todos', NOW(), NOW()),
  (gen_random_uuid()::text, 'todos.create', 'Create Todos', 'Create new todos', 'todos', 'todos', NOW(), NOW()),
  (gen_random_uuid()::text, 'todos.update', 'Update Todos', 'Update existing todos', 'todos', 'todos', NOW(), NOW()),
  (gen_random_uuid()::text, 'todos.delete', 'Delete Todos', 'Delete todos', 'todos', 'todos', NOW(), NOW()),
  (gen_random_uuid()::text, 'todos.assign', 'Assign Todos', 'Assign todos to other users', 'todos', 'todos', NOW(), NOW()),
  (gen_random_uuid()::text, 'issues.view', 'View Issues', 'View issues', 'issues', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'issues.create', 'Create Issues', 'Create issues', 'issues', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'issues.update', 'Update Issues', 'Update issues', 'issues', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'issues.delete', 'Delete Issues', 'Delete issues', 'issues', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'notes.view', 'View Notes', 'View notes', 'notes', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'notes.create', 'Create Notes', 'Create notes', 'notes', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'notes.update', 'Update Notes', 'Update notes', 'notes', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'notes.delete', 'Delete Notes', 'Delete notes', 'notes', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.users.view', 'View Users', 'View user list', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.users.create', 'Create Users', 'Create new users', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.users.update', 'Update Users', 'Update user details', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.users.delete', 'Delete Users', 'Delete users', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.groups.manage', 'Manage Groups', 'Create/edit/delete groups and assign permissions', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.permissions.view', 'View Permissions', 'View user and group permissions (read-only)', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.permissions.manage', 'Manage Permissions', 'View and manage user and group permissions', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.settings.manage', 'Modify System Settings', 'Modify system settings', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.jobs.view', 'View Background Jobs', 'View the background job queue and job details in admin', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'search.jobs.view', 'Search Background Jobs', 'Include background jobs in global fuzzy search (when implemented)', 'search', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.modules.manage', 'Manage Modules', 'Enable/disable modules', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.sessions.view', 'View Sessions', 'View user sessions', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.statistics.view', 'View Statistics', 'View system statistics', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.tickets.manage', 'Manage All Tickets', 'Full ticket management (admin view)', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.db.view', 'View Database Explorer', 'Access to the database explorer page', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.db.view_entries', 'View Database Entries', 'View entries in database tables', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.db.edit_entries', 'Edit Database Entries', 'Edit entries in database tables', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.db.delete_entries', 'Delete Database Entries', 'Delete entries from database tables', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'admin.db.query', 'Execute Database Queries', 'Execute SQL queries in the database explorer', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'audit.view', 'View Audit Log', 'View application audit log (who did what, when)', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'audit.export', 'Export Audit Log', 'Export audit log data', 'admin', NULL, NOW(), NOW()),
  (gen_random_uuid()::text, 'modules.tickets.view', 'View Tickets Module', 'Access to the Tickets module in navigation and dashboard', 'modules', 'tickets', NOW(), NOW()),
  (gen_random_uuid()::text, 'modules.timetracking.view', 'View Time Tracking Module', 'Access to the Time Tracking module in navigation and dashboard', 'modules', 'timetracking', NOW(), NOW()),
  (gen_random_uuid()::text, 'modules.todos.view', 'View ToDo Module', 'Access to the ToDo module in navigation and dashboard', 'modules', 'todos', NOW(), NOW()),
  (gen_random_uuid()::text, 'links.view', 'View Links', 'View bookmarks and links', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'links.create', 'Create Links', 'Create new bookmarks', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'links.update', 'Update Links', 'Update existing bookmarks', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'links.delete', 'Delete Links', 'Delete bookmarks', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'links.share', 'Share Links', 'Share individual links with other users', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'links.import', 'Import Links', 'Bulk import links from JSON or CSV', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'links.export', 'Export Links', 'Bulk export links to JSON or CSV', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'links.archive', 'Archive Links', 'Archive and unarchive links', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'collections.view', 'View Collections', 'View link collections', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'collections.create', 'Create Collections', 'Create new link collections', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'collections.update', 'Update Collections', 'Update existing collections', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'collections.delete', 'Delete Collections', 'Delete collections', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'collections.share', 'Share Collections', 'Share collections with other users', 'links', 'links', NOW(), NOW()),
  (gen_random_uuid()::text, 'modules.links.view', 'View Links Module', 'Access to the Links module in navigation and dashboard', 'modules', 'links', NOW(), NOW())
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  module = EXCLUDED.module,
  updated_at = NOW();
