// Human: Canonical client-side paths for React Router links, redirects, and active nav checks across the SPA.
// Agent: EXPORT const ROUTES frozen object; STRING literals only; CONSUMED by App routes Sidebar guards.

export const ROUTES = {
  HOME: "/",
  SETUP: "/setup",
  LOGIN: "/login",
  QR_LOGIN: "/qr-login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  BANNED: "/banned",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  ABOUT: "/about",
  CONTACT: "/contact",
  HEALTH: "/health",
  AGENT_STATISTICS: "/dashboard/statistics",
  ADMIN_USERS: "/dashboard/admin/users",
  ADMIN_MODULES: "/dashboard/admin/modules",
  ADMIN_GROUPS: "/dashboard/admin/groups",
  ADMIN_SETTINGS: "/dashboard/admin/settings",
  ADMIN_STATISTICS: "/dashboard/admin/statistics",
  ADMIN_SESSIONS: "/dashboard/admin/sessions",
  ADMIN_TICKETS: "/dashboard/admin/tickets",
  ADMIN_AUDIT: "/dashboard/admin/audit",
  ADMIN_AUDIT_DETAIL: "/dashboard/admin/audit/:id",
  ADMIN_DB_CONSOLE: "/dashboard/admin/db",
  ADMIN_BACKGROUND_JOBS: "/dashboard/admin/background-jobs",
  TIME_TRACKING: "/dashboard/time-tracking",
  TICKETS: "/dashboard/tickets",
  TODOS: "/dashboard/todos",
  TODOS_ARCHIVE: "/dashboard/todos/archive",
  LINKS: "/dashboard/links",
  LINKS_ARCHIVE: "/dashboard/links/archive",
  LINKS_COLLECTION: "/dashboard/links/collections",
  ARCHIVE: "/dashboard/archive",
  EMPLOYEES: "/dashboard/employees",
  EMPLOYEE_DETAIL: "/dashboard/employees/:id",
  CUSTOMERS: "/dashboard/customers",
  CUSTOMERS_ARCHIVE: "/dashboard/customers/archive",
  CUSTOMER_DETAIL: "/dashboard/customers/:id",
} as const;
